apiVersion: v1
kind: Pod
metadata:
  name: nfs-volume-test
  namespace: default
spec:
  containers:
  - name: nfs-volume-test
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: volv
      mountPath: /usr/share/nginx/html
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: nfs-client-pvc
